version: "3"

services:
  mariadb:
    build: ./srcs/mariadb/
    restart: unless-stopped
    volumes:
      - ${WEBROOT_PATH}/mariadb/:/var/db/mysql/
    networks:
      - default

  wordpress:
    build: ./srcs/wordpress/
    volumes:
      - ${WEBROOT_PATH}:/var/www/
    restart: unless-stopped
    networks:
      - default


  nginx:
    depends_on:
      - wordpress
    build: ./srcs/nginx/
    ports:
      - "443:443"
    volumes:
      - ${WEBROOT_PATH}:/var/www/
    restart: unless-stopped
    networks:
      - default

# this unnecercary step is brought to you by the people that wrote this unclear subject
networks:
  default:
    name: inception_default
