version: "3"



services:

  mariadb:
    build: ./srcs/mariadb/
    # restart: unless-stopped

  wordpress:
    build: ./srcs/wordpress/
    volumes:
      - ./webroot/:/var/www/
    ports:
      - "9000:9000"

  nginx:
    depends_on:
      - wordpress
    build: ./srcs/nginx/
    ports:
      - "443:443"
    volumes:
      - ./webroot/:/var/www/
    # restart: unless-stopped
    # restart: unless-stopped

# volumes:
#   type: bind
#   source: /tmp/webroot/
#   target: /var/www/
